use_frameworks!

target 'MathPod_Example' do
  pod 'MathPod', :path => '../'

  target 'MathPod_Tests' do
    pod 'MathPod', :path => '../'

    pod 'Quick', '~> 0.8'
  pod 'Nimble', '~> 3.0'
  end
end
